# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
# "$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[[mgr.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on = ["<Enter>"]
run = "plugin smart-enter"
desc = "Enter the child directory, or open the selected file"

[[mgr.prepend_keymap]]
on = ["<Backspace>"]
run = "leave"
desc = "Go back to the parent directory"

prepend_keymap = [
    # glow.yazi  ctrl+e , ctrl+y
    { on = ["<C-e>"], run = "seek 5" },
    { on = ["<C-y>"], run = "seek -5" },
]

[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin max-preview"
desc = "Maximize or restore preview"
