#[flavor]
#dark = "catppuccin-macchiato"

#[flavor]
#dark = "catppuccin-mocha"

#[flavor]
#light = "catppuccin-latte"

#[flavor]
#use = "tokyonight"

#[flavor]
#use = "onedark"

#[flavor]
#dark = "dracula"
