# By default, theme management is done using a plugin ( yatline.yazi )
# https://github.com/imsi32/yatline.yazi/wiki


#[flavor]
#dark = "catppuccin-macchiato"

#[flavor]
#dark = "catppuccin-frappe"

#[flavor]
#dark = "catppuccin-mocha"

#[flavor]
#light = "catppuccin-latte"

#[flavor]
#use = "tokyonight"

#[flavor]
#use = "onedark"

#[flavor]
#dark = "dracula"
