# ~/.config/yazi/yazi.toml
[manager]
linemode = "size_and_mtime"

[plugin]
prepend_previewers = [
  { name = "*.md", run = "glow" },
]

[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"
